import os

import psycopg
from psycopg.rows import dict_row

from ..utils.security import hash_password

DATABASE_URL = os.getenv(
    "DATABASE_URL", "postgresql://app_user:pg_password@localhost:5432/pg_management"
)


def get_db_connection():
    """Return a PostgreSQL connection whose rows can be used as dictionaries."""
    return psycopg.connect(DATABASE_URL, row_factory=dict_row)


def _is_empty(cursor, table_name: str) -> bool:
    cursor.execute(f"SELECT COUNT(*) AS count FROM {table_name}")
    return cursor.fetchone()["count"] == 0


def init_db():
    """Create the PostgreSQL schema and seed the initial application data."""
    with get_db_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS admins (
                    email TEXT PRIMARY KEY,
                    password TEXT NOT NULL
                )
            """)
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS rooms (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    number TEXT UNIQUE NOT NULL,
                    type TEXT NOT NULL,
                    rent DOUBLE PRECISION NOT NULL,
                    floor TEXT NOT NULL,
                    status TEXT NOT NULL
                )
            """)
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS tenants (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name TEXT NOT NULL,
                    email TEXT UNIQUE NOT NULL,
                    phone TEXT NOT NULL,
                    room TEXT NOT NULL,
                    "joinDate" TEXT NOT NULL,
                    "paymentStatus" TEXT NOT NULL,
                    password TEXT NOT NULL
                )
            """)
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS payments (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant TEXT NOT NULL,
                    amount DOUBLE PRECISION NOT NULL,
                    date TEXT NOT NULL,
                    method TEXT NOT NULL,
                    status TEXT NOT NULL
                )
            """)
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS complaints (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant TEXT NOT NULL,
                    room TEXT NOT NULL,
                    issue TEXT NOT NULL,
                    severity TEXT NOT NULL,
                    status TEXT NOT NULL
                )
            """)
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS outings (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant TEXT NOT NULL,
                    room TEXT NOT NULL,
                    "departureTime" TEXT NOT NULL,
                    "expectedReturnTime" TEXT NOT NULL,
                    "actualReturnTime" TEXT,
                    purpose TEXT NOT NULL,
                    status TEXT NOT NULL
                )
            """)

            cursor.execute("DELETE FROM admins WHERE email IN (%s, %s)", ("admin", "admin@gmail.com"))
            cursor.execute(
                "INSERT INTO admins (email, password) VALUES (%s, %s)",
                ("admin@gmail.com", hash_password("admin")),
            )

            if _is_empty(cursor, "rooms"):
                cursor.executemany(
                    "INSERT INTO rooms (id, number, type, rent, floor, status) VALUES (%s, %s, %s, %s, %s, %s)",
                    [(1, "101", "Single", 8500, "1st", "Occupied"), (2, "102", "Double Sharing", 6000, "1st", "Vacant"), (3, "201", "Single", 9000, "2nd", "Occupied"), (4, "202", "Triple Sharing", 4500, "2nd", "Maintenance"), (5, "301", "Double Sharing", 6500, "3rd", "Occupied")],
                )
            if _is_empty(cursor, "tenants"):
                cursor.executemany(
                    'INSERT INTO tenants (id, name, email, phone, room, "joinDate", "paymentStatus", password) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)',
                    [(1, "Alice Smith", "alice@example.com", "+91 9876543210", "101", "2026-01-10", "Paid", hash_password("tenant123")), (2, "Bob Johnson", "bob@example.com", "+91 8765432109", "201", "2026-03-15", "Pending", hash_password("tenant123")), (3, "Charlie Davis", "charlie@example.com", "+91 7654321098", "301", "2026-05-01", "Paid", hash_password("tenant123"))],
                )
            if _is_empty(cursor, "payments"):
                cursor.executemany(
                    "INSERT INTO payments (id, tenant, amount, date, method, status) VALUES (%s, %s, %s, %s, %s, %s)",
                    [(1, "Alice Smith", 8500, "2026-07-05", "UPI", "Success"), (2, "Charlie Davis", 6500, "2026-07-02", "Net Banking", "Success"), (3, "Bob Johnson", 9000, "2026-07-01", "Cash", "Pending")],
                )
            if _is_empty(cursor, "complaints"):
                cursor.executemany(
                    "INSERT INTO complaints (id, tenant, room, issue, severity, status) VALUES (%s, %s, %s, %s, %s, %s)",
                    [(1, "Bob Johnson", "201", "AC is leaking water", "High", "Pending"), (2, "Alice Smith", "101", "Wifi signal is weak in the corner", "Low", "Resolved")],
                )
            if _is_empty(cursor, "outings"):
                cursor.executemany(
                    'INSERT INTO outings (id, tenant, room, "departureTime", "expectedReturnTime", "actualReturnTime", purpose, status) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)',
                    [(1, "Alice Smith", "101", "2026-07-20T10:00", "2026-07-20T18:00", "2026-07-20T17:30", "Library Study", "Returned"), (2, "Bob Johnson", "201", "2026-07-20T14:30", "2026-07-20T21:30", None, "Dinner with friends", "Out")],
                )

            cursor.execute("SELECT email, password FROM admins")
            for row in cursor.fetchall():
                if not row["password"].startswith(("$2b$", "$2a$")):
                    cursor.execute("UPDATE admins SET password = %s WHERE email = %s", (hash_password(row["password"]), row["email"]))
            cursor.execute("SELECT id, password FROM tenants")
            for row in cursor.fetchall():
                if not row["password"].startswith(("$2b$", "$2a$")):
                    cursor.execute("UPDATE tenants SET password = %s WHERE id = %s", (hash_password(row["password"]), row["id"]))
